#!/bin/bash
# Windows 可执行文件打包脚本
# 注意：需要在 Windows 机器上运行，或使用 Docker/Wine

echo "========================================"
echo "Windows 独立可执行文件打包说明"
echo "========================================"
echo ""
echo "由于跨平台限制，需要在 Windows 机器上执行打包："
echo ""
echo "1. 在 Windows 机器上安装 Python 3.8+"
echo "2. 安装 PyInstaller:"
echo "   pip install pyinstaller"
echo ""
echo "3. 执行打包命令:"
echo "   cd Claude-Desktop-3P-Patch"
echo "   pyinstaller --onefile --name patch_claude_3p_windows ^"
echo "     --add-data \"resources;resources\" ^"
echo "     patch_claude_3p_windows.py"
echo ""
echo "4. 打包后的文件位于 dist/patch_claude_3p_windows.exe"
echo ""
echo "5. 将 patch_claude_3p_windows.exe 复制到 Windows-Delivery-Package/"
echo ""
echo "========================================"
echo ""
echo "替代方案：使用 GitHub Actions 自动打包"
echo ""
echo "创建 .github/workflows/build.yml："
echo "见项目文档"
echo ""
